# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1/Hardware/constraintsFiles/Connections.xdc

# Block Designs: bd/design_DIV/design_DIV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_DIV || ORIG_REF_NAME==design_DIV} -quiet] -quiet

# IP: bd/design_DIV/ip/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_DIV_floating_point_0_0 || ORIG_REF_NAME==design_DIV_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_MAC/design_MAC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MAC || ORIG_REF_NAME==design_MAC} -quiet] -quiet

# IP: bd/design_MAC/ip/design_MAC_floating_point_0_0/design_MAC_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MAC_floating_point_0_0 || ORIG_REF_NAME==design_MAC_floating_point_0_0} -quiet] -quiet

# Block Designs: bd/design_BRAM_D/design_BRAM_D.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_D || ORIG_REF_NAME==design_BRAM_D} -quiet] -quiet

# IP: bd/design_BRAM_D/ip/design_BRAM_D_blk_mem_gen_0_0/design_BRAM_D_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_D_blk_mem_gen_0_0 || ORIG_REF_NAME==design_BRAM_D_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/design_BRAM_C/design_BRAM_C.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_C || ORIG_REF_NAME==design_BRAM_C} -quiet] -quiet

# IP: bd/design_BRAM_C/ip/design_BRAM_C_blk_mem_gen_0_0/design_BRAM_C_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_C_blk_mem_gen_0_0 || ORIG_REF_NAME==design_BRAM_C_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/design_BRAM_B/design_BRAM_B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_B || ORIG_REF_NAME==design_BRAM_B} -quiet] -quiet

# IP: bd/design_BRAM_B/ip/design_BRAM_B_blk_mem_gen_0_0/design_BRAM_B_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_B_blk_mem_gen_0_0 || ORIG_REF_NAME==design_BRAM_B_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/design_BRAM_A/design_BRAM_A.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_A || ORIG_REF_NAME==design_BRAM_A} -quiet] -quiet

# IP: bd/design_BRAM_A/ip/design_BRAM_A_blk_mem_gen_0_1/design_BRAM_A_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_A_blk_mem_gen_0_1 || ORIG_REF_NAME==design_BRAM_A_blk_mem_gen_0_1} -quiet] -quiet

# Block Designs: bd/design_CTRL/design_CTRL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CTRL || ORIG_REF_NAME==design_CTRL} -quiet] -quiet

# IP: bd/design_CTRL/ip/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CTRL_blk_mem_gen_0_0 || ORIG_REF_NAME==design_CTRL_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/design_DIV/design_DIV_ooc.xdc

# XDC: bd/design_MAC/design_MAC_ooc.xdc

# XDC: bd/design_BRAM_D/design_BRAM_D_ooc.xdc

# XDC: bd/design_BRAM_C/design_BRAM_C_ooc.xdc

# XDC: bd/design_BRAM_B/design_BRAM_B_ooc.xdc

# XDC: bd/design_BRAM_A/design_BRAM_A_ooc.xdc

# XDC: bd/design_CTRL/design_CTRL_ooc.xdc
