# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.cache/wt [current_project]
set_property parent.project_path C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_ip_project/Hardware/LUD_v3_1_ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/imports/hdl/design_101_wrapper.vhd
add_files C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/design_101.bd
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_zynq_ultra_ps_e_0_0/design_101_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_zynq_ultra_ps_e_0_0/design_101_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_D_blk_mem_gen_0_0/design_BRAM_D_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_blk_mem_gen_0_1/design_BRAM_A_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_B_blk_mem_gen_0_0/design_BRAM_B_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_C_blk_mem_gen_0_0/design_BRAM_C_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/Connections.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_DIV_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_MAC_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_D_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_C_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_B_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_rst_ps8_0_100M_0/design_101_rst_ps8_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_rst_ps8_0_100M_0/design_101_rst_ps8_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_rst_ps8_0_100M_0/design_101_rst_ps8_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_clk_wiz_0_0/design_101_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_clk_wiz_0_0/design_101_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_clk_wiz_0_0/design_101_clk_wiz_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_auto_ds_0/design_101_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_auto_ds_0/design_101_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_auto_ds_0/design_101_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/ip/design_101_auto_pc_0/design_101_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_1_test/LUD_v3_1_test.srcs/sources_1/bd/design_101/design_101_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_101_wrapper -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_101_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_101_wrapper_utilization_synth.rpt -pb design_101_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
