# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/ip/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0.xci
# IP: The module: 'design_DIV_floating_point_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/ip/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_DIV_floating_point_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/ip/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0.xci
# IP: The module: 'design_DIV_floating_point_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/ip/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_DIV_floating_point_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
