# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/ip/design_BRAM_A_blk_mem_gen_0_1/design_BRAM_A_blk_mem_gen_0_1.xci
# IP: The module: 'design_BRAM_A_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/ip/design_BRAM_A_blk_mem_gen_0_1/design_BRAM_A_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_BRAM_A_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/ip/design_BRAM_A_blk_mem_gen_0_1/design_BRAM_A_blk_mem_gen_0_1.xci
# IP: The module: 'design_BRAM_A_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anuragchoudhury/mod_v_fix_v2_md_2018_ip/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/ip/design_BRAM_A_blk_mem_gen_0_1/design_BRAM_A_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_BRAM_A_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
