# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/design_101_myip_LUdecomposition_0_0.xci
# IP: The module: 'design_101_myip_LUdecomposition_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CTRL_blk_mem_gen_0_0 || ORIG_REF_NAME==design_CTRL_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_DIV_floating_point_0_0 || ORIG_REF_NAME==design_DIV_floating_point_0_0} -quiet] -quiet

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_MAC_floating_point_0_0/design_MAC_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MAC_floating_point_0_0 || ORIG_REF_NAME==design_MAC_floating_point_0_0} -quiet] -quiet

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_blk_mem_gen_0_0/design_BRAM_A_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_A_blk_mem_gen_0_0 || ORIG_REF_NAME==design_BRAM_A_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_blk_mem_gen_0_0/design_BRAM_A_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/Connections.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_101_myip_LUdecomposition_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_DIV_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_MAC_ooc.xdc

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/design_101_myip_LUdecomposition_0_0.xci
# IP: The module: 'design_101_myip_LUdecomposition_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CTRL_blk_mem_gen_0_0 || ORIG_REF_NAME==design_CTRL_blk_mem_gen_0_0} -quiet] -quiet

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_DIV_floating_point_0_0 || ORIG_REF_NAME==design_DIV_floating_point_0_0} -quiet] -quiet

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_MAC_floating_point_0_0/design_MAC_floating_point_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_MAC_floating_point_0_0 || ORIG_REF_NAME==design_MAC_floating_point_0_0} -quiet] -quiet

# IP: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_blk_mem_gen_0_0/design_BRAM_A_blk_mem_gen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_BRAM_A_blk_mem_gen_0_0 || ORIG_REF_NAME==design_BRAM_A_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_blk_mem_gen_0_0/design_BRAM_A_blk_mem_gen_0_0_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/Connections.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_101_myip_LUdecomposition_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_CTRL_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_BRAM_A_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_DIV_ooc.xdc

# XDC: c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_4_test/LUD_v3_4_test.srcs/sources_1/bd/design_101/ip/design_101_myip_LUdecomposition_0_0/src/design_MAC_ooc.xdc
