# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.cache/wt [current_project]
set_property parent.project_path C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/LUD_v3_1_ip
  c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/lud_ip_v2
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/autoHdlFiles/types.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/hdlFiles/regs.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/hdlFiles/quadBRAM.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/new/bram_ZYNQ_mux.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/new/bram_ZYNQ_decoder.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/autoHdlFiles/MUX_AU_IN.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/autoHdlFiles/MUX_BRAM_IN.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/autoHdlFiles/LUDHardware.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/hdlFiles/hardwareTester.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/hdlFiles/hardwareTesterWrapper.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/new/myip_LUdecomposition_v2_v1_0_S00_AXI.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/new/myip_LUdecomposition_v2_v1_0.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/imports/hdl/design_CTRL_wrapper.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/imports/hdl/design_BRAM_A_wrapper.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/imports/hdl/design_DIV_wrapper.vhd
  C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/imports/hdl/design_MAC_wrapper.vhd
}
add_files C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_CTRL/design_CTRL.bd
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_CTRL/ip/design_CTRL_blk_mem_gen_0_0/design_CTRL_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_CTRL/design_CTRL_ooc.xdc]

add_files C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/design_BRAM_A.bd
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/ip/design_BRAM_A_blk_mem_gen_0_0/design_BRAM_A_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_BRAM_A/design_BRAM_A_ooc.xdc]

add_files C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/design_DIV.bd
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/ip/design_DIV_floating_point_0_0/design_DIV_floating_point_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_DIV/design_DIV_ooc.xdc]

add_files C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_MAC/design_MAC.bd
set_property used_in_implementation false [get_files -all c:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_MAC/ip/design_MAC_floating_point_0_0/design_MAC_floating_point_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/vivadoProjects/project_LUDH/project_LUDH.srcs/sources_1/bd/design_MAC/design_MAC_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/constraintsFiles/Connections.xdc
set_property used_in_implementation false [get_files C:/Users/anuragchoudhury/Desktop/local_documents/Vivado/LUD_v3_5_ip_project/Hardware/constraintsFiles/Connections.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top myip_LUdecomposition_v2_v1_0 -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef myip_LUdecomposition_v2_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file myip_LUdecomposition_v2_v1_0_utilization_synth.rpt -pb myip_LUdecomposition_v2_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
