# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_101/design_101.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101 || ORIG_REF_NAME==design_101} -quiet] -quiet

# IP: bd/design_101/ip/design_101_zynq_ultra_ps_e_0_0/design_101_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_101_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_myip_LUdecomposition_0_0/design_101_myip_LUdecomposition_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_myip_LUdecomposition_0_0 || ORIG_REF_NAME==design_101_myip_LUdecomposition_0_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_ps8_0_axi_periph_0/design_101_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_ps8_0_axi_periph_0 || ORIG_REF_NAME==design_101_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_rst_ps8_0_100M_0/design_101_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_rst_ps8_0_100M_0 || ORIG_REF_NAME==design_101_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_auto_ds_0/design_101_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_auto_ds_0 || ORIG_REF_NAME==design_101_auto_ds_0} -quiet] -quiet

# IP: bd/design_101/ip/design_101_auto_pc_0/design_101_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_101_auto_pc_0 || ORIG_REF_NAME==design_101_auto_pc_0} -quiet] -quiet

# XDC: bd/design_101/design_101_ooc.xdc
